kijho_mailer_layout:
    path:     /
    defaults: { _controller: KijhoMailerBundle:Layout:index }

kijho_mailer_layout_new:
    path:     /new
    defaults: { _controller: KijhoMailerBundle:Layout:new }
    
kijho_mailer_layout_save:
    path:     /save
    defaults: { _controller: KijhoMailerBundle:Layout:save }
    methods: [POST]
    
kijho_mailer_layout_edit:
    path:     /{layoutId}/edit
    defaults: { _controller: KijhoMailerBundle:Layout:edit }
    
kijho_mailer_layout_update:
    path:     /{layoutId}/update
    defaults: { _controller: KijhoMailerBundle:Layout:update }
    methods: [POST]
    
kijho_mailer_layout_preview:
    path:     /{layoutId}/preview
    defaults: { _controller: KijhoMailerBundle:Layout:preview }
    
kijho_mailer_layout_delete:
    path:     /delete
    defaults: { _controller: KijhoMailerBundle:Layout:delete }
    methods: [POST]