kijho_mailer_homepage:
    path:     /home
    defaults: { _controller: KijhoMailerBundle:Default:home }
    
kijho_mailer_layout:
    resource: "@KijhoMailerBundle/Resources/config/routing/layout.yml"
    prefix:   /layout
    
kijho_mailer_template:
    resource: "@KijhoMailerBundle/Resources/config/routing/template.yml"
    prefix:   /template

