services:
    email_manager:
        class: Kijho\MailerBundle\Services\EmailManager
        arguments: [@request_stack, @mailer, @service_container, @doctrine.orm.entity_manager]
        scope: request
